version: '3.8'
services:
  api:
    container_name: 'wallet-relayer-backend'
    image: 'wallet-relayer-backend'
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: ['yarn', 'start:prod']
    ports:
      - 8000:8000
    networks:
      - nestjs-network
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: wallet-relayer-nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=80
      - BACKEND_PORT=8000
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - nestjs-network
networks:
  nestjs-network:
