version: '3.8'
services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - '3306:3306'
    networks:
      - my_network

networks:
  my_network:
